#:kivy 2.2.1
<MyGridLayout>:

    name: name
    pizza: pizza
    colour:colour

    cols: 1
    GridLayout:
        cols: 2
        size: root.width, root.height
        Label:
            text: "name"
        TextInput:
            id: name
            multiline: False

        Label:
            text: "favorite pizza"
        TextInput:
            id: pizza
            multiline: False

        Label:
            text: "favorite colour"
        TextInput:
            id: colour
            multiline: False

    Button:
        text: "Submit"
        font_size: 32
        on_press: root.press()
