#:kivy 2.3.0
#:import utils kivy.utils
<Home>:
    Screen:
        name: "eqn"

        MDTextFieldRect:
            id: month
            size_hint: None, None
            width: 300
            height: "30dp"
            background_color: app.theme_cls.bg_normal
            pos_hint: {"center_x":.5, "center_y":.6}
            hint_text: "Final value of x"
    
        MDTextFieldRect:
            id: year
            size_hint: None, None
            width: 300
            height: "30dp"
            background_color: app.theme_cls.bg_normal
            pos_hint: {"center_x":.5, "center_y":.5}
            hint_text: "Number of Domain for y"
    
        MDRaisedButton:
            text: "Generate the Graph"
            pos_hint: {"center_x":.5, "center_y":.35}
            on_release: root.plot_monthly_water_intake();root.plot_yearly_water_intake();root.current = "graph"
            # on_release: root.current = "graph"

    Screen:
        name: "graph"
        # ScrollView:
        #     bar_width: "10dp"  # Adjust the width of the scrollbar
        #     bar_color: 0, 0, 1, 1  # Adjust the color of the scrollbar
        #     size_hint: 1, 1
        
        BoxLayout:
            id:bx1
            orientation: 'vertical'
            # pos_hint: {"top":1}
            size_hint_y:.9
            size_hint: (.7, 0.9)
            pos_hint: {'center_x': 0.5, "top":1}
            spacing: 10

        MDRaisedButton:
            text: "Back to Home Screen"
            pos_hint: {"center_x":.5, "y":.02}
            on_release: root.current = "eqn"; bx1.clear_widgets()